title: Luxury Apartments in Corning NY | Fairport Ridge Apartments
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Fairport Ridge Apartments is a luxurious apartment complex located in Big Flats, near Corning NY.
url: "" # the base hostname & protocol for your site, e.g. http://example.com
